openapi: 3.0.0
info:
  title: Nomiq API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0
servers:
  - url: https://nomiq.trap.jp/api
    description: Main server
  - url: http://localhost:8080
    description: Local test server

paths:
  /ping:
    get:
      summary: "pong"
      responses:
        "200":
          description: successfully ping
          content:
            application/json:
              schema:
                type: string
                example: "pong"
        "403":
          description: Not authorized
        "500":
          description: Internal server error
        default:
          description: Unexpected Error
