openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0
servers:
  - url: https://nomiq.trap.jp/api
    description: Main server
  - url: http://localhost:8080
    description: Local test server

paths:
  /users:
    get:
      summary: 全ユーザの取得
      responses:
        "200": # status code
          description: A JSON array of user objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                      example: "alter"
                    traQid:
                      type: string
                      format: uuid
